pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  outDir: $(Build.ArtifactStagingDirectory)

steps:
- script: dotnet build ./src/git-istage.sln --configuration $(buildConfiguration) --output $(outDir) /nologo
  displayName: 'dotnet build $(buildConfiguration)'
