global using FluentAssertions;
global using Xunit;
global using GitIStage.Commands;
global using GitIStage.Patches;
global using GitIStage.Patches.EntryHeaders;
global using GitIStage.Patches.HunkLines;
global using GitIStage.Services;
global using GitIStage.Tests.Infrastructure;
global using GitIStage.Text;